// Emits src/api/enums.generated.js from the real @raycast/api type definitions, so Icon / Color /
// Toast.Style / Keyboard and friends carry the exact string values extensions compare against.
//
//   node gen-enums.mjs
//
// Run it after bumping the @raycast/api devDependency, then `node build.mjs`.

import { readFileSync, writeFileSync } from "node:fs";

const dts = readFileSync("node_modules/@raycast/api/types/index.d.ts", "utf8").replace(/\r\n/g, "\n");

/// Walk the declaration file tracking `namespace`/`enum` nesting by brace depth, collecting every
/// enum member. Namespaced enums are keyed by their dotted path (`Image.Mask`), and a namespace that
/// only re-binds a top-level enum (`const Style: typeof ToastStyle_2;`) is recorded as an alias.
function collectEnums(source) {
  const lines = source.split("\n");
  const scopes = [];
  const enums = new Map();
  const aliases = new Map();
  let depth = 0;
  let current = null;

  for (const line of lines) {
    const namespaceMatch = /^\s*(?:export\s+)?declare\s+namespace\s+([A-Za-z0-9_]+)\s*\{/.exec(line);
    const enumMatch = /^\s*(?:export\s+)?(?:declare\s+)?enum\s+([A-Za-z0-9_]+)\s*\{/.exec(line);
    const aliasMatch = /^\s*(?:export\s+)?const\s+([A-Za-z0-9_]+)\s*:\s*typeof\s+([A-Za-z0-9_.]+)\s*;/.exec(line);

    if (!current && enumMatch) {
      const path = [...scopes.map((scope) => scope.name), enumMatch[1]].join(".");
      current = { path, members: [], startDepth: depth };
      enums.set(path, current.members);
      depth += 1;
      continue;
    }
    if (!current && namespaceMatch) {
      scopes.push({ name: namespaceMatch[1], depth });
      depth += 1;
      continue;
    }
    if (!current && aliasMatch && scopes.length) {
      aliases.set([...scopes.map((scope) => scope.name), aliasMatch[1]].join("."), aliasMatch[2]);
      continue;
    }

    if (current) {
      const member = /^\s*([A-Za-z0-9_]+)\s*=\s*"([^"]*)"/.exec(line);
      if (member) current.members.push([member[1], member[2]]);
    }

    for (const char of line) {
      if (char === "{") depth += 1;
      else if (char === "}") {
        depth -= 1;
        if (current && depth === current.startDepth) current = null;
        while (scopes.length && depth <= scopes[scopes.length - 1].depth) scopes.pop();
      }
    }
  }
  return { enums, aliases };
}

// `Foo_2` duplicates are the declaration file's way of disambiguating the List/Grid variants of the
// same public enum, and of hoisting a namespaced one to the top level.
const publicPath = (path) => path.replace(/_\d+(\.|$)/g, "$1");

const { enums: rawEnums, aliases } = collectEnums(dts);
const supportedNamespaces = new Set(["Alert", "Image", "Toast", "WindowManagement"]);
const enums = new Map();
for (const [path, members] of rawEnums) {
  if (!members.length) continue;
  const clean = publicPath(path);
  if (clean.includes(".") && !supportedNamespaces.has(clean.split(".")[0])) continue;
  if (!enums.has(clean)) enums.set(clean, members);
}
for (const [path, target] of aliases) {
  if (!supportedNamespaces.has(publicPath(path).split(".")[0])) continue;
  const members = enums.get(publicPath(target));
  if (members && !enums.has(path)) enums.set(path, members);
}

function literal(members) {
  return `Object.freeze({\n${members.map(([name, value]) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)},`).join("\n")}\n})`;
}

const lines = [
  "// Generated by gen-enums.mjs from @raycast/api's type definitions — do not edit by hand.",
  "",
];

const roots = [...enums.keys()].filter((path) => !path.includes("."));
for (const path of roots) {
  lines.push(`export const ${path} = ${literal(enums.get(path))};`, "");
}

const nested = {};
for (const [path, members] of enums) {
  if (!path.includes(".")) continue;
  const [scope, ...rest] = path.split(".");
  nested[scope] = nested[scope] || [];
  nested[scope].push([rest.join("."), members]);
}
lines.push("export const nestedEnums = {");
for (const scope of Object.keys(nested).sort()) {
  lines.push(`  ${JSON.stringify(scope)}: {`);
  for (const [name, members] of nested[scope]) {
    lines.push(`    ${JSON.stringify(name)}: ${literal(members).replace(/\n/g, "\n    ")},`);
  }
  lines.push("  },");
}
lines.push("};", "");

writeFileSync("src/api/enums.generated.js", lines.join("\n"));

const total = [...enums.values()].reduce((sum, members) => sum + members.length, 0);
console.log(`enums.generated.js: ${enums.size} enums, ${total} members`);
console.log([...enums.keys()].join(", "));
